export type CampusBuilding = {
  id: string;
  name: string;
  campusKey: 'carleton' | 'uottawa' | 'algonquin';
  lat: number;
  lng: number;
  aliases?: string[];
};

export const CAMPUS_BUILDINGS: CampusBuilding[] = [
  // ── Carleton University ────────────────────────────────────────────────────
  {
    id: 'carleton_tory',
    name: 'Tory Building',
    campusKey: 'carleton',
    lat: 45.3840,
    lng: -75.6965,
    aliases: ['Tory', 'TB'],
  },
  {
    id: 'carleton_loeb',
    name: 'Loeb Building',
    campusKey: 'carleton',
    lat: 45.3846,
    lng: -75.6975,
    aliases: ['Loeb', 'Loeb Bldg', 'LA'],
  },
  {
    id: 'carleton_steacie',
    name: 'Steacie Building',
    campusKey: 'carleton',
    lat: 45.3860,
    lng: -75.6983,
    aliases: ['Steacie', 'SC'],
  },
  {
    id: 'carleton_mackenzie',
    name: 'Mackenzie Building',
    campusKey: 'carleton',
    lat: 45.3868,
    lng: -75.6961,
    aliases: ['Mackenzie', 'ME', 'MC'],
  },
  {
    id: 'carleton_minto_case',
    name: 'Minto CASE',
    campusKey: 'carleton',
    lat: 45.3874,
    lng: -75.6956,
    aliases: ['CASE', 'Minto Centre'],
  },
  {
    id: 'carleton_herzberg',
    name: 'Herzberg Laboratories',
    campusKey: 'carleton',
    lat: 45.3856,
    lng: -75.6990,
    aliases: ['Herzberg', 'HP'],
  },
  {
    id: 'carleton_richcraft',
    name: 'Richcraft Hall',
    campusKey: 'carleton',
    lat: 45.3851,
    lng: -75.6957,
    aliases: ['Richcraft', 'RB'],
  },
  {
    id: 'carleton_robertson',
    name: 'Robertson Hall',
    campusKey: 'carleton',
    lat: 45.3836,
    lng: -75.6972,
    aliases: ['Robertson', 'RO'],
  },
  {
    id: 'carleton_nicol',
    name: 'Nicol Building',
    campusKey: 'carleton',
    lat: 45.3832,
    lng: -75.6961,
    aliases: ['Nicol', 'NI'],
  },
  {
    id: 'carleton_architecture',
    name: 'Architecture Building',
    campusKey: 'carleton',
    lat: 45.3862,
    lng: -75.6972,
    aliases: ['Architecture', 'AA'],
  },
  {
    id: 'carleton_azrieli',
    name: 'Azrieli Pavilion',
    campusKey: 'carleton',
    lat: 45.3866,
    lng: -75.6968,
    aliases: ['Azrieli', 'AZ'],
  },
  {
    id: 'carleton_macodrum',
    name: 'MacOdrum Library',
    campusKey: 'carleton',
    lat: 45.3845,
    lng: -75.6967,
    aliases: ['Library', 'MAC', 'MacOdrum'],
  },
  {
    id: 'carleton_athletics',
    name: 'Athletics',
    campusKey: 'carleton',
    lat: 45.3831,
    lng: -75.6988,
    aliases: ['Athletic Centre', 'Carleton gym', 'CU Athletics'],
  },
  {
    id: 'carleton_university_centre',
    name: 'University Centre',
    campusKey: 'carleton',
    lat: 45.3844,
    lng: -75.6980,
    aliases: ['UC', 'Student Centre'],
  },
  {
    id: 'carleton_residence_commons',
    name: 'Residence Commons',
    campusKey: 'carleton',
    lat: 45.3820,
    lng: -75.6973,
    aliases: ['Res Commons', 'Dining Hall'],
  },
  {
    id: 'carleton_southam',
    name: 'Southam Hall',
    campusKey: 'carleton',
    lat: 45.3857,
    lng: -75.6950,
    aliases: ['Southam', 'SA'],
  },
  {
    id: 'carleton_paterson',
    name: 'Paterson Hall',
    campusKey: 'carleton',
    lat: 45.3841,
    lng: -75.6958,
    aliases: ['Paterson', 'PA'],
  },
  {
    id: 'carleton_me_building',
    name: 'ME Building',
    campusKey: 'carleton',
    lat: 45.3870,
    lng: -75.6967,
    aliases: ['Mechanical Engineering', 'ME'],
  },
  {
    id: 'carleton_canal',
    name: 'Canal Building',
    campusKey: 'carleton',
    lat: 45.3826,
    lng: -75.6955,
    aliases: ['Canal', 'CB'],
  },
  {
    id: 'carleton_arise',
    name: 'ARISE Building',
    campusKey: 'carleton',
    lat: 45.3879,
    lng: -75.6960,
    aliases: ['ARISE', 'Advanced Research'],
  },
  {
    id: 'carleton_health_sciences',
    name: 'Health Sciences Building',
    campusKey: 'carleton',
    lat: 45.3853,
    lng: -75.6944,
    aliases: ['Health Sciences', 'HS', 'HSB'],
  },
  {
    id: 'carleton_river',
    name: 'River Building',
    campusKey: 'carleton',
    lat: 45.3836,
    lng: -75.6948,
    aliases: ['River', 'RB'],
  },
  {
    id: 'carleton_dunton_tower',
    name: 'Dunton Tower',
    campusKey: 'carleton',
    lat: 45.3849,
    lng: -75.6956,
    aliases: ['Dunton', 'DT'],
  },

  // ── University of Ottawa ───────────────────────────────────────────────────
  {
    id: 'uottawa_tabaret',
    name: 'Tabaret Hall',
    campusKey: 'uottawa',
    lat: 45.4231,
    lng: -75.6833,
    aliases: ['Tabaret', 'TBT'],
  },
  {
    id: 'uottawa_morisset',
    name: 'Morisset Library',
    campusKey: 'uottawa',
    lat: 45.4228,
    lng: -75.6841,
    aliases: ['Morisset', 'Library', 'MRT'],
  },
  {
    id: 'uottawa_fss',
    name: 'FSS',
    campusKey: 'uottawa',
    lat: 45.4224,
    lng: -75.6823,
    aliases: ['Faculty of Social Sciences', 'Social Sciences', 'FSS Building'],
  },
  {
    id: 'uottawa_crx',
    name: 'CRX',
    campusKey: 'uottawa',
    lat: 45.4219,
    lng: -75.6843,
    aliases: ['Learning Crossroads', 'Crossroads', 'CRX Building'],
  },
  {
    id: 'uottawa_stem',
    name: 'STEM Complex',
    campusKey: 'uottawa',
    lat: 45.4214,
    lng: -75.6852,
    aliases: ['STEM', 'Science Complex'],
  },
  {
    id: 'uottawa_marion',
    name: 'Marion Hall',
    campusKey: 'uottawa',
    lat: 45.4237,
    lng: -75.6855,
    aliases: ['Marion', 'MRN'],
  },
  {
    id: 'uottawa_vanier',
    name: 'Vanier Hall',
    campusKey: 'uottawa',
    lat: 45.4233,
    lng: -75.6827,
    aliases: ['Vanier', 'VNR'],
  },
  {
    id: 'uottawa_lamoureux',
    name: 'Lamoureux Hall',
    campusKey: 'uottawa',
    lat: 45.4240,
    lng: -75.6820,
    aliases: ['Lamoureux', 'LMX'],
  },
  {
    id: 'uottawa_hagen',
    name: 'Hagen Hall',
    campusKey: 'uottawa',
    lat: 45.4226,
    lng: -75.6815,
    aliases: ['Hagen', 'HGN'],
  },
  {
    id: 'uottawa_lees',
    name: 'Lees Campus',
    campusKey: 'uottawa',
    lat: 45.4103,
    lng: -75.6609,
    aliases: ['Lees', 'Lees Avenue', 'Health Sciences Lees'],
  },
  {
    id: 'uottawa_montpetit',
    name: 'Montpetit Hall',
    campusKey: 'uottawa',
    lat: 45.4222,
    lng: -75.6836,
    aliases: ['Montpetit', 'MNT'],
  },
  {
    id: 'uottawa_roger_guindon',
    name: 'Roger Guindon Hall',
    campusKey: 'uottawa',
    lat: 45.4088,
    lng: -75.6618,
    aliases: ['Roger Guindon', 'Guindon', 'RGN'],
  },
  {
    id: 'uottawa_desmarais',
    name: 'Desmarais Building',
    campusKey: 'uottawa',
    lat: 45.4244,
    lng: -75.6836,
    aliases: ['Desmarais', 'DMS'],
  },
  {
    id: 'uottawa_colonel_by',
    name: 'Colonel By Hall',
    campusKey: 'uottawa',
    lat: 45.4221,
    lng: -75.6860,
    aliases: ['Colonel By', 'CBY'],
  },
  {
    id: 'uottawa_minto_sports',
    name: 'Minto Sports Complex',
    campusKey: 'uottawa',
    lat: 45.4210,
    lng: -75.6844,
    aliases: ['Minto', 'Minto Complex', 'uOttawa gym'],
  },

  // ── Algonquin College ──────────────────────────────────────────────────────
  {
    id: 'algonquin_a',
    name: 'A Building',
    campusKey: 'algonquin',
    lat: 45.3490,
    lng: -75.7583,
    aliases: ['Building A', 'A Block'],
  },
  {
    id: 'algonquin_b',
    name: 'B Building',
    campusKey: 'algonquin',
    lat: 45.3487,
    lng: -75.7576,
    aliases: ['Building B', 'B Block'],
  },
  {
    id: 'algonquin_c',
    name: 'C Building',
    campusKey: 'algonquin',
    lat: 45.3484,
    lng: -75.7568,
    aliases: ['Building C', 'C Block'],
  },
  {
    id: 'algonquin_e',
    name: 'E Building',
    campusKey: 'algonquin',
    lat: 45.3481,
    lng: -75.7560,
    aliases: ['Building E', 'E Block'],
  },
  {
    id: 'algonquin_h',
    name: 'H Building',
    campusKey: 'algonquin',
    lat: 45.3494,
    lng: -75.7571,
    aliases: ['Building H', 'H Block'],
  },
  {
    id: 'algonquin_j',
    name: 'J Building',
    campusKey: 'algonquin',
    lat: 45.3498,
    lng: -75.7564,
    aliases: ['Building J', 'J Block'],
  },
  {
    id: 'algonquin_k',
    name: 'K Building',
    campusKey: 'algonquin',
    lat: 45.3501,
    lng: -75.7557,
    aliases: ['Building K', 'K Block'],
  },
  {
    id: 'algonquin_n',
    name: 'N Building',
    campusKey: 'algonquin',
    lat: 45.3478,
    lng: -75.7574,
    aliases: ['ACCE', 'Construction Trades', 'Building N'],
  },
  {
    id: 'algonquin_p',
    name: 'P Building',
    campusKey: 'algonquin',
    lat: 45.3475,
    lng: -75.7565,
    aliases: ['DARE District', 'DARE', 'Building P'],
  },
  {
    id: 'algonquin_t',
    name: 'T Building',
    campusKey: 'algonquin',
    lat: 45.3504,
    lng: -75.7550,
    aliases: ['Building T', 'T Block'],
  },
  {
    id: 'algonquin_arc',
    name: 'ARC',
    campusKey: 'algonquin',
    lat: 45.3507,
    lng: -75.7543,
    aliases: ['Algonquin Residence', 'Residence and Conference Centre', 'Residence'],
  },
  {
    id: 'algonquin_student_commons',
    name: 'Student Commons',
    campusKey: 'algonquin',
    lat: 45.3488,
    lng: -75.7582,
    aliases: ['Commons', 'Student Centre', 'SC'],
  },
];

/** Look up a building by its exact id. */
export function findBuilding(id: string): CampusBuilding | null {
  return CAMPUS_BUILDINGS.find(b => b.id === id) ?? null;
}

/**
 * Search buildings by name or alias, optionally filtered to a campus.
 * Case-insensitive substring match on name and all aliases.
 */
export function searchBuildings(query: string, campusKey?: string): CampusBuilding[] {
  if (!query) return campusKey ? CAMPUS_BUILDINGS.filter(b => b.campusKey === campusKey) : [];
  const needle = query.toLowerCase();
  return CAMPUS_BUILDINGS.filter(b => {
    if (campusKey && b.campusKey !== campusKey) return false;
    if (b.name.toLowerCase().includes(needle)) return true;
    return (b.aliases ?? []).some(a => a.toLowerCase().includes(needle));
  });
}
